#!/bin/sh
PIDFILE="/run/auto-night-detection.pid"

status()
{
if [ -f /var/run/auto-toggle-nightvision ]; then echo "enabled";  fi
}

start()
{
  LOG=/dev/null
  echo "enabling auto toggle nightvision"
  touch /var/run/auto-toggle-nightvision
}

stop()
{
  echo "disabling auto toggle nightvision"
  rm /var/run/auto-toggle-nightvision

}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

