#!/bin/sh

## Get OSD-Information
if [ -f /system/sdcard/config/osd ]; then
    source /system/sdcard/config/osd  2>/dev/null
	/system/sdcard/bin/setconf -k o -v "${OSD}" 2>/dev/null
    /system/sdcard/bin/setconf -k c -v ${COLOR} 2>/dev/null
    /system/sdcard/bin/setconf -k s -v ${SIZE} 2>/dev/null
    /system/sdcard/bin/setconf -k x -v ${POSY} 2>/dev/null
    /system/sdcard/bin/setconf -k w -v ${FIXEDW} 2>/dev/null
	/system/sdcard/bin/setconf -k p -v ${SPACE} 2>/dev/null
fi
