#!/bin/sh
# Motion detection (must be set before the server starting)
# Set the socket option in order to restart easily the server (socket in use)
echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle

if [ -f /system/sdcard/config/motion ] ; then
    source /system/sdcard/config/motion 2>/dev/null
    /system/sdcard/bin/setconf -k r -v ${Region} 2>/dev/null
    /system/sdcard/bin/setconf -k m -v ${Sens} 2>/dev/null
    /system/sdcard/bin/setconf -k z -v ${OsdColor} 2>/dev/null
fi;

