#!/bin/sh
PIDFILE="/run/recording.pid"
DCIM_PATH="/system/sdcard/DCIM"
[ -f /system/sdcard/config/rtspserver.conf ] && . /system/sdcard/config/rtspserver.conf

## UserName and password
[ "$USERNAME" != "" ] && CREDENTIALS="$USERNAME:$USERPASSWORD@"

[ ! -d "$DCIM_PATH" ] && mkdir -p $DCIM_PATH

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  [ "$pid" ] && kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
}

start()
{
  if [ -f $PIDFILE ]; then
    echo "Recording already running.";
  else
    echo "Started recording."
    SUB_DIR="$(date +%m%dFANG)"
    [ ! -d "$DCIM_PATH/$SUB_DIR" ] && mkdir -p "$DCIM_PATH/$SUB_DIR"
    FILE_NAME="MOV_$(date +%H%M.h264)"
    RECORDING_PATH="$DCIM_PATH/$SUB_DIR/$FILE_NAME"
    # wait for rtspserver to become available
    until pids=$(pidof v4l2rtspserver-master)
    do
      sleep 1
    done
    /system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://"$CREDENTIALS"0.0.0.0:8554/unicast -strict experimental -y -vcodec copy -an $RECORDING_PATH &>/dev/null &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid"
    rm "$PIDFILE" 1> /dev/null 2>&1
    echo "Stopped recording."
  else
    echo "Could not find a running recording to stop."
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
      $1
      ;;
  esac
fi
