#!/bin/sh
PIDFILE="/run/recording.pid"
DCIM_PATH="/system/sdcard/DCIM"

if [ ! -d "$DCIM_PATH" ]; then
  mkdir -p $DCIM_PATH
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if [ -f $PIDFILE ]; then
    echo "Recording already running.";
  else
    echo "Started recording."
    SUB_DIR="$(date +%m%dFANG)"
    if [ ! -d "$DCIM_PATH/$SUB_DIR" ]; then
      mkdir -p "$DCIM_PATH/$SUB_DIR"
    fi
    FILE_NAME="MOV_$(date +%H%M.h264)"
    RECORDING_PATH="$DCIM_PATH/$SUB_DIR/$FILE_NAME"
    # wait for rtspserver to become available
    until pids=$(pidof v4l2rtspserver-master)
    do
      sleep 1
    done
    /system/sdcard/bin/busybox nohup /system/sdcard/bin/avconv -flags low_delay -fflags nobuffer -probesize 32 -i rtsp://0.0.0.0:8554/unicast -strict experimental -y -vcodec copy -an $RECORDING_PATH &>/dev/null &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid" &&  rm "$PIDFILE"
    echo "Stopped recording."
  else
    echo "Could not find a running recording to stop."
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
      $1
      ;;
  esac
fi
