#!/bin/sh
PIDFILE="/run/v4l2rtspserver-master-mjpeg.pid"
LOGDIR="/tmp"
LOGPATH="$LOGDIR/v4l2rtspserver-master.log"
export LD_LIBRARY_PATH='/system/sdcard/lib:/thirdlib:/system/lib'

[ ! -f /system/sdcard/config/rtspserver.conf ] && cp /system/sdcard/config/rtspserver.conf.dist /system/sdcard/config/rtspserver.conf

[ -f /system/sdcard/config/rtspserver.conf ] && . /system/sdcard/config/rtspserver.conf

[ -f /system/sdcard/config/osd.conf ] && . /system/sdcard/config/osd.conf 2>/dev/null

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
  [ "$pid" ] && kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
}

start()
{
  if [ "$(status)" != "" ]; then
    echo "A v4l2rtspserver is already running, please stop it or reboot"
  else
    echo "Starting v4l2rtspserver-master with parameter -fMJPG"
    /system/sdcard/controlscripts/rtsp-h264 stop

    ## Configure OSD
    [ -f /system/sdcard/controlscripts/configureOsd ] && . /system/sdcard/controlscripts/configureOsd  2>/dev/null

    ## Configure Motion
    [ -f /system/sdcard/controlscripts/configureMotion ] && . /system/sdcard/controlscripts/configureMotion  2>/dev/null
    ## Bitrate
    /system/sdcard/bin/setconf -k b -v ${BITRATE} 2>/dev/null

    ## Framerate
    [ "$FRAMERATE_DEN" != "" ] && [ "$FRAMERATE_NUM" != "" ] && /system/sdcard/bin/setconf -k d -v "$FRAMERATE_NUM,$FRAMERATE_DEN" 2>/dev/null

    ## Audio
    if [ "$AUDIOFORMAT" != "OFF" ] ; then
        AUDIOPARAM="-E $AUDIOFORMAT:$AUDIOINBR:$AUDIOOUTBR"
        /system/sdcard/bin/setconf -k h -v "$HWVOLUME" 2>/dev/null
        /system/sdcard/bin/setconf -k i -v "$SWVOLUME" 2>/dev/null
        /system/sdcard/bin/setconf -k q -v "$FILTER" 2>/dev/null
        /system/sdcard/bin/setconf -k l -v "$HIGHPASSFILTER" 2>/dev/null
        /system/sdcard/bin/setconf -k a -v "$AECFILTER" 2>/dev/null
    else
        AUDIOPARAM="-A"
    fi

    ## Video format
    [ "$VIDEOFORMAT" != "" ] && VIDEOFORMAT="-r $VIDEOFORMAT"

    ## UserName and password
    [ "$USERNAME" != "" ] && CREDENTIAL="-U $USERNAME:$USERPASSWORD"

    ## Port
    [ "$PORT" != "" ] && PORT="-P $PORT"

    ## FLIP
    if [ "$FLIP" == "ON" ]; then
        /system/sdcard/bin/setconf -k f -v 1
    elif [ "$FLIP" == "OFF" ]; then
        /system/sdcard/bin/setconf -k f -v 0
    fi

    echo "================== START ===============" >> "$LOGPATH"
    echo "/system/sdcard/bin/v4l2rtspserver-master -fMJPG $RTSPMJPEGOPTS  $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT" >> "$LOGPATH"
    /system/sdcard/bin/v4l2rtspserver-master -fMJPG $RTSPMJPEGOPTS  $AUDIOPARAM $VIDEOFORMAT $CREDENTIAL $PORT  2>> "$LOGPATH" >> "$LOGPATH" &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid"
    rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
