#!/bin/sh
PIDFILE="/run/v4l2rtspserver-master-h264-s.pid"
NIGHTFILE="/run/v4l2rtspserver-master-h264-s.night"
export LD_LIBRARY_PATH='/thirdlib:/system/lib'

if [ -f /system/sdcard/config/osd ]; then
source /system/sdcard/config/osd  2>/dev/null
fi


status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
if  ls /var/run/v4l2rtspserver*  1> /dev/null 2>&1; then
echo "A v4l2rtspserver is already running, please stop it or reboot"
else
  LOG=/dev/null
  echo "v4l2rtspserver-master with parameter -S"
        /system/sdcard/controlscripts/rtsp-mjpeg stop
        /system/sdcard/controlscripts/rtsp-h264 stop
        killall v4l2rtspserver-master # As the run.sh starts a v4l2rtspserver as well
      /system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master $OSD -S &>/dev/null &
  echo "$!" > "$PIDFILE"
fi
}


startnight()
{
if  ls /var/run/v4l2rtspserver*  1> /dev/null 2>&1; then
echo "A v4l2rtspserver is already running, please stop it or reboot"
else
  LOG=/dev/null
  echo "v4l2rtspserver-master with parameter -S -n"
        /system/sdcard/controlscripts/rtsp-mjpeg stop
        /system/sdcard/controlscripts/rtsp-h264 stop
  	touch $NIGHTFILE
      	/system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master $OSD -S -n &>/dev/null &
  echo "$!" > "$PIDFILE"
fi
}


stop()
{
  rm $NIGHTFILE  1> /dev/null 2>&1
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid &  rm "$PIDFILE"  1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|startnight|stop|status)
    $1
    ;;
  esac
fi
