#!/bin/sh
PIDFILE="/run/v4l2rtspserver-master-mjpeg.pid"
export LD_LIBRARY_PATH='/thirdlib:/system/lib'

if [ -f /system/sdcard/config/rtspserver.conf ]; then
  . /system/sdcard/config/rtspserver.conf
fi

if [ -f /system/sdcard/config/osd ]; then
  . /system/sdcard/config/osd 2>/dev/null
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    # Prints PID: $pid if exists and returns 0(no error) else returns 1(error condition)
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if  ls /var/run/v4l2rtspserver* 1> /dev/null 2>&1; then
    echo "A v4l2rtspserver is already running, please stop it or reboot"
  else
    echo "Starting v4l2rtspserver-master with parameter -fMJPG"
    /system/sdcard/controlscripts/rtsp-h264 stop

    ## Configure OSD
    if [ -f /system/sdcard/controlscripts/configureOsd ]; then
      . /system/sdcard/controlscripts/configureOsd  2>/dev/null
    fi

    ## Configure Motion
    if [ -f /system/sdcard/controlscripts/configureMotion ]; then
      . /system/sdcard/controlscripts/configureMotion  2>/dev/null
    fi
    /system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master -fMJPG $RTSPMJPEGOPTS &>/dev/null &
    echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid" & rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
