#!/bin/sh
PIDFILE="/run/v4l2rtspserver-master-h264.pid"
CONFIGPATH="/system/sdcard/config"
export LD_LIBRARY_PATH='/thirdlib:/system/lib'

if [ -f /system/sdcard/config/osd ]; then
  source /system/sdcard/config/osd 2>/dev/null
fi

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  if ls /var/run/v4l2rtspserver* 1> /dev/null 2>&1; then
    echo "A v4l2rtspserver is already running, please stop it or reboot"
  else
    echo "Starting v4l2rtspserver-master"
      /system/sdcard/controlscripts/rtsp-mjpeg stop
      killall v4l2rtspserver-master # As the run.sh starts a v4l2rtspserver as well
      ## Configure OSD
      if [ -f /system/sdcard/controlscripts/configureOsd ]; then
        source /system/sdcard/controlscripts/configureOsd  2>/dev/null
      fi

      ## Configure Motion
      if [ -f /system/sdcard/controlscripts/configureMotion ]; then
        source /system/sdcard/controlscripts/configureMotion  2>/dev/null
      fi
      video_size="$(cat "$CONFIGPATH/video_size.conf")"
	  /system/sdcard/bin/busybox nohup /system/sdcard/bin/v4l2rtspserver-master "$video_size" &>/dev/null &
      echo "$!" > "$PIDFILE"
  fi
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill "$pid" & rm "$PIDFILE" 1> /dev/null 2>&1
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|startnight|stop|status)
    $1
    ;;
  esac
fi

