#!/bin/sh

PIDFILE='/run/timelapse.pid'

status()
{
	pid="$(cat "$PIDFILE" 2>/dev/null)"
	if [ "$pid" ]; then
		kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
	fi
}

start()
{
	if [ -f "$PIDFILE" ]; then
		echo "Timelapse already running";
	else
		echo "Starting Timelapse"
		/system/sdcard/bin/busybox nohup /system/sdcard/scripts/timelapse.sh &>/dev/null &
		echo "$!" > "$PIDFILE"
	fi
}

stop()
{
	pid="$(cat "$PIDFILE" 2>/dev/null)"
	if [ "$pid" ]; then
		kill "$pid" && rm "$PIDFILE"
	fi
}

if [ $# -eq 0 ]; then
	start
else
	case $1 in start|stop|status)
		$1
		;;
	esac
fi

