#!/bin/sh
PIDFILE='/run/timelapse.pid'

status()
{  PID=$(cat $PIDFILE)
   if [ "$PID" != "" ]; then
   cat $PIDFILE
   fi
}

start()
{
  LOG=/dev/null
  echo "Starting timelapse"
  /system/sdcard/bin/busybox nohup /system/sdcard/scripts/timelapse.sh &> /dev/null &
  PID=$!
  echo $PID > $PIDFILE
  echo $PID
}

stop()
{ 
  PID=$(cat $PIDFILE)
  kill -9 $PID
  rm $PIDFILE
  cd /system/sdcard/DCIM/timelapse/$(date +%Y-%m-%d)
  /system/sdcard/bin/avconv -y -r 30 -f image2 -i img%03d.jpg  $(date +%Y-%m-%d_%H%M%S).mov
  rm *.jpg
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi
